[package]
name = "benchmark_uhttp_tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
httparse = "1"
bytes = "*"
futures = "0.3"
memchr = "*"
mio = { version = "1", features = ["os-poll", "net"] }
may = "*"
async-std = "1.12.0"
tokio = { version = "*", features = ["full"] }
once_cell = "*"