[package]
name = "uhttp"
version = "0.11.0"
edition = "2024"
description = "Simple http server for humans"
license = "MIT"
repository = "https://github.com/alshdavid/uhttp"

[features]
anyhow = ["dep:anyhow"]
json = ["dep:serde", "dep:serde_json"]
router = ["dep:percent-encoding", "dep:path-tree"]
http2 = ["dep:tokio-rustls", "dep:rustls-pemfile"]
websocket = ["dep:sha1", "dep:base64", "dep:tokio-tungstenite"]

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1"] }
hyper-util = { workspace = true, features = ["server-graceful", "server-auto"] }
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "net"] }
tokio-util = { workspace = true, features = ["io", "io-util", "futures-util"] }

tokio-rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }

# Optional dependencies for JSON support
anyhow = { workspace = true, optional = true }

# Optional dependencies for JSON support
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }

# Optional dependencies for router support
path-tree = { workspace = true, optional = true }
percent-encoding = { workspace = true, optional = true }

# Optional dependencies for websocket support
base64 = { workspace = true, optional = true }
sha1 = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }
