[package]
name = "uhttp_example_tokio"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "foo"
path = "./src/main.rs"

[dependencies]
bytes = "0.5"
http = "0.2"
httparse = "1.2"
log = "0.4"
may = "0.3"
time = "0.2"
lazy_static = "1"
num_cpus = "*"