[package]
name = "uhttp_example_factory"
version = "0.1.0"
edition = "2024"

[dependencies]
uhttp = { path = "../../crates/uhttp" }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
