[package]
name = "uhttp_example_tokio_minihttp"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "=0.4"
futures = "=0.1.11"
httparse = "*"
log = "=0.3.6"
net2 = "=0.2"
time = "=0.1"
tokio-core = "*"
tokio-io = "=0.1"
tokio-proto = "=0.1"
tokio-service = "=0.1"