[package]
name = "uhttp_example_file_server_include_dir"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
uhttp = { path = "../../crates/uhttp", features = [
  "file_server",
  "file_server_include_dir",
] }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
include_dir = { workspace = true }
