[package]
name = "uhttp"
version = "0.1.0"
edition = "2021"

[lib]
name = "uhttp"

[[bench]]
name = "benchmarks"
harness = false
path = "src/bench.rs"

[dependencies]
httparse = "1"
bytes = "*"
may = "*"


[dev-dependencies]
divan = "0.*"
