[package]
name = "uhttp_example_basic"
version = "0.1.0"
edition = "2024"

[dependencies]
uhttp = { path = "../../crates/uhttp" }
tokio = { version = "*", features = ["full"] }
anyhow = "*"
async_fn_traits = "0.1.1"
